kiniela: &kiniela
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  timeout: 5000

development:
  <<: *kiniela
  database: kiniela_development

test: &test
  <<: *kiniela
  database: kiniela_test

production:
  <<: *kiniela
  database: kiniela_development

cucumber:
  <<: *test